## (Hypothesis Testing)

In [ ]:
import pandas as pd
from scipy import stats
import numpy as np
import statistics as sta


### Que 1. 
### A F&B manager wants to determine whether there is any significant difference in the diameter of the cutlet between two units. A randomly selected sample of cutlets was collected from both units and measured? Analyze the data and draw inferences at 5% significance level. Please state the assumptions and tests that you carried out to check validity of the assumptions.

In [ ]:
data = pd.read_csv('/content/Cutlets.csv')
data.head(6)

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522
5  7.3871  6.8110

In [ ]:
data.shape

(35, 2)

In [ ]:
data.describe()

Unit A     Unit B
count  35.000000  35.000000
mean    7.019091   6.964297
std     0.288408   0.343401
min     6.437600   6.038000
25%     6.831500   6.753600
50%     6.943800   6.939900
75%     7.280550   7.195000
max     7.516900   7.545900

In [ ]:
data.isna().sum()

Unit A    0
Unit B    0
dtype: int64

In [ ]:
unit_a = pd.Series(data.iloc[:,0])
unit_a.head(6)

0    6.8090
1    6.4376
2    6.9157
3    7.3012
4    7.4488
5    7.3871
Name: Unit A, dtype: float64

In [ ]:
unit_b = pd.Series(data.iloc[:,1])
unit_b.head(6)

0    6.7703
1    7.5093
2    6.7300
3    6.7878
4    7.1522
5    6.8110
Name: Unit B, dtype: float64

In [ ]:
T_value, P_value = stats.ttest_ind(a=unit_a,b=unit_b) # 2 Sample T-Test
print('T_value:',T_value)
print('P_value:',P_value)

T_value: 0.7228688704678061
P_value: 0.4722394724599501


In [ ]:
## Null Hypothesis = There is no significant differance between the average diameter of the cutlet between two units.
## Alternate Hypothesis = There is significant differance between the average diameter of the cutlet between two units.

In [ ]:
if P_value<0.05:
 print('we reject the null hypothesis saying that There is significant difference between the average diameter of the cutlet between two units')
else:
 print('we do not reject the null hypothesis saying that There is no significant difference between the average diameter of the cutlet between two units')

we do not reject the null hypothesis saying that There is no significant differance between the average diameter of the cutlet between two units


### Que 2. 
### A hospital wants to determine whether there is any difference in the average Turn Around Time (TAT) of reports of the laboratories on their preferred list. They collected a random sample and recorded TAT for reports of 4 laboratories. TAT is defined as sample collected to report dispatch.       Analyze the data and determine whether there is any difference in average TAT among the different laboratories at 5% significance level.

In [ ]:
lab_data = pd.read_csv('/content/LabTAT.csv')
lab_data.head(6)

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60
5        179.45        197.00        181.51        161.12

In [ ]:
lab_data.shape

(120, 4)

In [ ]:
lab_data.isna().sum()

Laboratory 1    0
Laboratory 2    0
Laboratory 3    0
Laboratory 4    0
dtype: int64

In [ ]:
lab_data.describe()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
count    120.000000    120.000000    120.000000     120.00000
mean     178.361583    178.902917    199.913250     163.68275
std       13.173594     14.957114     16.539033      15.08508
min      138.300000    140.550000    159.690000     124.06000
25%      170.335000    168.025000    188.232500     154.05000
50%      178.530000    178.870000    199.805000     164.42500
75%      186.535000    189.112500    211.332500     172.88250
max      216.390000    217.860000    238.700000     205.18000

In [ ]:
Laboratory_1 = pd.Series(lab_data.iloc[:,0])
Laboratory_1.head(6)

0    185.35
1    170.49
2    192.77
3    177.33
4    193.41
5    179.45
Name: Laboratory 1, dtype: float64

In [ ]:
Laboratory_2 = pd.Series(lab_data.iloc[:,1])
Laboratory_2.head(6)

0    165.53
1    185.91
2    194.92
3    183.00
4    169.57
5    197.00
Name: Laboratory 2, dtype: float64

In [ ]:
Laboratory_3 = pd.Series(lab_data.iloc[:,2])
Laboratory_3.head(6)

0    176.70
1    198.45
2    201.23
3    199.61
4    204.63
5    181.51
Name: Laboratory 3, dtype: float64

In [ ]:
Laboratory_4 = pd.Series(lab_data.iloc[:,3])
Laboratory_4.head(6)

0    166.13
1    160.79
2    185.18
3    176.42
4    152.60
5    161.12
Name: Laboratory 4, dtype: float64

In [ ]:
T_value, P_value = stats.f_oneway(Laboratory_1,Laboratory_2,Laboratory_3,Laboratory_4) # ANOVA Test
T_value, P_value

print('T_value:',T_value)
print('P_value:',P_value)

T_value: 118.70421654401437
P_value: 2.1156708949992414e-57


In [ ]:
## Null Hypothesis = There is no significant differance between the average TAT among the different laboratories.
## Alternate Hypothesis = There is significant differance between the average TAT among the different laboratories.

In [ ]:
if P_value<0.05:
 print('we reject the null hypothesis saying that There is significant difference between the average TAT among the different laboratories')
else:
 print('we do not reject the null hypothesis saying that There is no significant difference between the average TAT among the different laboratories')

we do not reject the null hypothesis saying that There is no significant difference between the average TAT among the different laboratories


### Que 3.
### Sales of products in four different regions is tabulated for males and females. Find if male-female buyer rations are similar across regions

In [ ]:
sales_data= pd.read_csv('/content/BuyerRatio.csv')
sales_data

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [ ]:
## Null Hypothesis = All proportions are equal.
## Alternate Hypothesis = Not All proportions are equal.

In [ ]:
a =sales_data.iloc[:,1:5].astype(int)
a.dtypes

East     int64
West     int64
North    int64
South    int64
dtype: object

In [ ]:
chi2_score, P_value ,dof ,expected_table = stats.chi2_contingency(observed =sales_data.iloc[:,1:5].astype(int)) # Chi-Squaqre Test
print('Chi-squared value:',chi2_score)
print('P-value          :',P_value)
print('Degree of freedom:',dof)
print('expected_value   :\n',expected_table)

Chi-squared value: 1.595945538661058
P-value          : 0.6603094907091882
Degree of freedom: 3
expected_value   :
 [[  42.76531299  146.81287862  131.11756787   72.30424052]
 [ 442.23468701 1518.18712138 1355.88243213  747.69575948]]


In [ ]:
if P_value<0.05:
 print('we reject the null hypothesis saying that Not All proportions are equal')
else:
 print('we do not reject the null hypothesis saying that All proportions are equal')

we do not reject the null hypothesis saying that All proportions are equal


### Que 4.
### TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain % of the customer order forms. Any error in order form renders it defective and has to be reworked before processing. The manager wants to check whether the defective % varies by centre. Please analyze the data at 5% significance level and help the manager draw appropriate inferences

In [ ]:
customer_data = pd.read_csv('/content/Costomer+OrderForm.csv')
customer_data.head(6)

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free
5   Error Free  Error Free  Error Free  Error Free

In [ ]:
customer_data.describe(include='all')

Phillippines   Indonesia       Malta       India
count           300         300         300         300
unique            2           2           2           2
top      Error Free  Error Free  Error Free  Error Free
freq            271         267         269         280

In [ ]:
customer_data.Phillippines.value_counts()


Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [ ]:
customer_data.Indonesia.value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [ ]:
customer_data.Malta.value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [ ]:
customer_data.India.value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [ ]:
cust_group_data = np.array([[271,267,269,280],[29,33,31,20]])
cust_group_data

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [ ]:
chi2_score, P_value ,dof ,expected_table = stats.chi2_contingency(observed =cust_group_data) # Chi-Squaqre Test
print('Chi-squared value:',chi2_score)
print('P-value          :',P_value)
print('Degree of freedom:',dof)
print('expected_value   :\n',expected_table)

Chi-squared value: 3.858960685820355
P-value          : 0.2771020991233135
Degree of freedom: 3
expected_value   :
 [[271.75 271.75 271.75 271.75]
 [ 28.25  28.25  28.25  28.25]]


In [ ]:
if P_value<0.05:
 print('we reject the null hypothesis saying that defective % varies by center')
else:
 print('we do not reject the null hypothesis saying that defective % not varies by center')
 

we do not reject the null hypothesis saying that defective % not varies by center
